packages:
  - 'plugins'
  - 'profiles/*'
allowBuilds:
  '"': true
  ',': true
  '-': true
  /: true
  '@': true
  '@code-yeongyu/comment-checker': set this to true or false
  '[': true
  ']': true
  a: true
  c: true
  d: true
  e: true
  g: true
  h: true
  k: true
  m: true
  msgpackr-extract: set this to true or false
  n: true
  o: true
  oh-my-openagent: set this to true or false
  p: true
  r: true
  s: true
  t: true
  u: true
  x: true
  y: true
